version: '3.4'

services:
  database:
    image: postgres:latest
    container_name: "Database"
    ports:
      - 6000:5432
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  auth:
    image: auth
    command: dotnet Auth.dll /seed
    build:
      context: .
      dockerfile: Auth/Dockerfile
    ports:
      - 7000:80
      - 7001:443
    depends_on:
      - database
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - database
      - auth